# Generated by Django 4.2.1 on 2023-05-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_files_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
