# Generated by Django 4.2.1 on 2023-05-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_files_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='image',
            new_name='file_pdf',
        ),
    ]
